# Playbook para reboot hosts OTDM, utilizando o módulo reboot do Ansible. 
# O playbook é configurado para ser executado em todos os hosts definidos no inventário,
# mas a tarefa de reboot será aplicada apenas aos hosts que pertencem aos grupos 'otdm_homol' ou 'otdm_producao',
# conforme definido nas variáveis de inventário. O playbook ignora erros durante o processo de reboot para garantir 
# que a execução continue mesmo se algum host não puder ser reiniciado com sucesso.
---
- name: Reboot Hosts OTDM
  hosts: all
  gather_facts: false

  vars_files:
    # Arquivo de variáveis para inventários
    - vars/playbook_vars_inventarios.yml
      
  tasks:
    - name: Reboot dos hosts OTDM
      ansible.builtin.reboot:
      ignore_errors: yes
      when: inventory_hostname in otdm_homol or inventory_hostname in otdm_producao