---
- name: Start CloudCMD — Homologação
  hosts: hxjs03.energia.org.br
  become: true
  gather_facts: false

  tasks:
    - name: Start CloudCMD
      ansible.builtin.command:
        cmd: ./recicla_cloudcmd start
        chdir: /opt/aplicacoes/cloudcmd/scripts
      become_user: usrcloudcmd
      async: 600     
      poll: 5
      changed_when: true
      failed_when: false
      
