# Playbook para gerenciar ssl.conf e reiniciar Apache
# após atualizações de segurança. Desabilita a configuração
# SSL existente renomeando com timestamp e inicia o serviço.
---
- name: Gerenciamento do arquivo ssl.conf e start nos servidores Apache
  hosts: "{{ servidores }}"
  gather_facts: false
  vars:
    # Valor padrão caso 'servidores' não seja fornecido
    servidores: all
    
    ssl_conf_path: "/etc/httpd/conf.d/ssl.conf"
    timestamped_suffix: "{{ ansible_date_time.date }}_{{ ansible_date_time.time | replace(':', '-') }}"
    renamed_ssl_conf_path: "{{ ssl_conf_path }}.disable_{{ timestamped_suffix }}"

  tasks:
    - name: Bloco de teste
      block:
        - name: Verificar se o arquivo ssl.conf existe
          ansible.builtin.stat:
            path: "{{ ssl_conf_path }}"
          register: ssl_conf_exists

        - name: Renomear ssl.conf para ssl.conf.disable com timestamp
          ansible.builtin.command:
            cmd: mv "{{ ssl_conf_path }}" "{{ renamed_ssl_conf_path }}"
          when: ssl_conf_exists.stat.exists

        - name: Verificar e iniciar o serviço Apache, se necessário
          ansible.builtin.service:
            name: httpd
            state: started
          register: apache_status
          failed_when: apache_status.failed
      when: "'hxap' in inventory_hostname or 'pxap' in inventory_hostname or 'lab-aut0' in inventory_hostname"

    - name: Notificar resultado da execução
      ansible.builtin.debug:
        msg: "Apache foi iniciado com sucesso no host {{ inventory_hostname }}"
      when: apache_status.changed