---
- name: OTDM PRODUÇÃO/PRODUÇÃO
  hosts: localhost
  gather_facts: false

  vars:
    otdm_lab: [hxms05.energia.org.br,hxms06.energia.org.br,hxms07.energia.org.br,hxsc07.energia.org.br,
        hxsc08.energia.org.br,hxsc09.energia.org.br,hxsc10.energia.org.br,hxsc11.energia.org.br,
        hxsc12.energia.org.br]
  
  vars_files:
    - vars/playbook_comandos_start_otdm_prod_producao.yml
    - vars/playbook_comandos_start_otdm_naoprod_lab.yml

  tasks:
    - name: INICIALIZAÇÃO DE SERVIÇOS
      block:
        - name: Configurações pré-start hadoop
          loop: "{{ comandos_producao }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_hadoop_del_format.yml
          when: item.nome == 'Start hadoop'
          
        - name: Inicializando serviços PRODUÇÃO
          loop: "{{ comandos_producao }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_start_java.yml

        - name: Verificandos serviços JAVA PRODUÇÃO
          loop: "{{ comandos_producao }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_status_java.yml
      when: ambiente == 'PROD'

    - name: Ambiente LAB
      block:
        - name: Iniciando serviços LAB
          loop: "{{ comandos_lab }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_start_java.yml

        - name: Verificandos serviços JAVA LAB
          loop: "{{ comandos_lab }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_status_java.yml
      when: ambiente == 'LAB'