---
- name: Stop TinGED — Homologação (hxdk02)
  hosts: hxdk02.energia.org.br
  become: true
  gather_facts: false

  tasks:
    - name: Stop GED (TinGED)
      ansible.builtin.command:
        cmd: docker-compose down
        chdir: /opt/project/docker-compose-alfresco
      async: 600
      poll: 5
      
    - name: Stop Monitoramento (TinGED)
      ansible.builtin.command:
        cmd: docker-compose down
        chdir: /opt/project/monitoramento
      async: 600
      poll: 5
      
