---
- name: Play coletor de facts
  hosts: all
  #gather_facts: true
  gather_facts: false
  #tasks: []
  tasks:
    - name: Setup
      ansible.builtin.setup:
        gather_subset:
          - '!all,!min'
          - local