---
- name: Instalar yum-utils, executar yum update e reiniciar se necessário
  hosts: "{{ servidores }}"
  gather_facts: false
  vars:
    # Valor padrão caso 'servidores' não seja fornecido
    servidores: all

  tasks:
    - name: Instalar o pacote
      ansible.builtin.yum:
        name: java-1.8.0-openjdk-devel
        state: present