---
- name: STOP SERVIÇOS LINUX
  hosts: localhost
  gather_facts: false
  
  vars_files:
    - vars/playbook_comandos_stop_linux.yml

  tasks:
    - name: Ambiente NÃO PRODUÇÃO
      block:
        - name: Parando serviços NÃO PRODUÇÃO
          loop: "{{ comandos_naoprod }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_stop_java.yml

        - name: Ambiente NÃO PRODUÇÃO GED
          loop: "{{ comandos_naoprod }}"
          ansible.builtin.shell: "{{ item.comando }}"
          args:
            chdir: "{{ item.diretorio }}"
          when: item.nome == 'Stop GED'
      when: ambiente == 'NAO_PROD'

    - name: Ambiente PRODUÇÃO
      block:
        - name: Parando serviços PRODUÇÃO
          loop: "{{ comandos_prod }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_stop_java.yml

        - name: Ambiente PRODUÇÃO GED
          loop: "{{ comandos_prod }}"
          ansible.builtin.shell: "{{ item.comando }}"
          args:
            chdir: "{{ item.diretorio }}"
          when: item.nome == 'Stop GED'
      when: ambiente == 'PROD'

    - name: Ambiente LAB
      block:
        - name: Parando serviços LAB
          loop: "{{ comandos_lab }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_stop_java.yml
      when: ambiente == 'LAB'