---
- name: OTDM NÃO PRODUÇÃO/HOMOLOGAÇÃO
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/playbook_comandos_stop_otdm_naoprod_homol.yml
    - vars/playbook_comandos_stop_otdm_naoprod_lab.yml

  tasks:
    - name: PARADA DE SERVIÇOS
      block:
        - name: Parando serviços HOMOLOGAÇÃO
          loop: "{{ comandos_homologacao }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_stop_java.yml       
      when: ambiente == 'HOMOL'

    - name: Ambiente LAB
      block:
        - name: Parando serviços LAB
          loop: "{{ comandos_lab }}"
          ansible.builtin.include_tasks:
            file: tasks/playbook_task_stop_java.yml
      when: ambiente == 'LAB'