---
- name: Start HomGED — Homologação (hxdk01)
  hosts: hxdk01.energia.org.br
  become: true
  gather_facts: false

  tasks:
    - name: Start GED (HomGED)
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /opt/project/docker-compose-alfresco
      async: 600
      poll: 5

    - name: Start Monitoramento (HomGED)
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /opt/project/monitoramento
      async: 600
      poll: 5
