---
- name: STOP JS7 — HOMOLOGAÇÃO (hxwl02)
  hosts: hxwl02.energia.org.br
  become: true
  become_user: usrjobscheduler
  gather_facts: false

  vars:
    jetty_dir: /home/usrjobscheduler/sos-berlin.com/js7/joc/jetty/bin
    controller_dir: /opt/aplicacoes/js7/controller/bin

  tasks:
    - name: Stop JOC/Jetty
      ansible.builtin.command: ./jetty.sh stop
      args:
        chdir: "{{ jetty_dir }}"
      failed_when: false

    - name: Stop Controller
      ansible.builtin.command: ./controller.sh stop
      args:
        chdir: "{{ controller_dir }}"
      failed_when: false